### ISSUE TITLE
parse error for deadkey with ]

### ISSUE THREAD

**Issue by bitoj** [cajhin/capsicain#17]
I recently found this very useful project, while I was searching for an alternative for AutoHotkey that passes through my local keyboard lay-out to my remote work environment, where I do not have administrator rights.

So far I am pleased. There are, however, a few minor inconveniences that force me to retrain my muscle memory, because I cannot remap certain key combinations that I had defined in AHK.

One limitation seems to be a bug in parsing a COMBO definition with a hotkey and ], as demonstrated in the following fragment.

```
[config_1]
option configname demo ]
option debug
rewire apps mod9 apps
combo           ; [& .... ....] > deadkey(;)
combo deadkey-; E [. ...^ ...^] > altchar(0235) # ë
combo deadkey-; E [. ...| ...|] > altchar(0203) # Ë
combo deadkey-; [ [. ...^ ...^] > altchar(0147) # “
combo deadkey-; ] [. ...^ ...^] > altchar(0148) # ” PARSE ERROR
combo           ] [. ...^ ...^] > altchar(0148) # ” works
```

This results in error message

```
Cannot parse combo rule: deadkey-; ] [. ...^ ...^] > altchar(0148)
```

**Comment by cajhin** [comment]
this should be fixed with the v83 beta from the x64/release directory.
Please confirm if this works with your config

**Comment by bitoj** [comment]
confirmed
