### ISSUE TITLE
parse error for moddedkey(NP+

### ISSUE THREAD

**Issue by bitoj** [cajhin/capsicain#18]
While recreating some previous AHK key combinations, I stumbled upon a parse error when I tried to use function `moddedkey` to define a combination with `NP+` as in the following fragment.

```
[config_1]
option configname demo moddedkey NP+
rewire numlock mod13 numlock
combo - [& .... .... ..&.] > moddedkey(NP- + &.&.)
combo = [& .... .... ..&.] > moddedkey(NP+ + &.&.) # PARSE ERROR
```

The results in error

```
Cannot parse combo rule: combo = [& .... .... ..&.] > moddedkey(NP+ + &.&.)
```

So far this does not seem to be preventing me from reaching my goal, for the following use of function `sequence` seems to be a workaround.
```
combo = [& .... .... ..&.] > sequence(&LCTRL_&LALT_&NP+_^NP+_^LALT_^LCTRL)
```

FYI: the combination `Ctrl+NumLock` is received when I press the `Pause` key in the top right corner of my keyboard without modifiers.

**Comment by cajhin** [comment]
same; this is very likely a very silly bug. Will be fixed soon.

**Comment by cajhin** [comment]
fixed with v83 beta

**Comment by bitoj** [comment]
confirmed
