### ISSUE TITLE
ALPHA_FROM and ALPHA_TO lists are different size?

### ISSUE THREAD

**Issue by mittsquared** [cajhin/capsicain#35]
I'm trying to use capsicain to remap my laptop keyboard to colemak. From the wiki, it seems like it should be simple. For some reason, the program cannot parse my alpha list. Here is my config file.

```
﻿GLOBAL IniVersion v1
GLOBAL ActiveConfigOnStartup 1

[CONFIG_1]
OPTION configName = colemak
OPTION Debug
ALPHA_FROM
  Q W E R T   Y U I O P
  A S D F G   H J K L ;
  Z X C V B   N M
ALPHA_TO
  Q W F P G   J L U Y ;
  A R S T D   H N E I O
  Z X C V B   K M
ALPHA_END
```

Clearly, the lists are the same size. Am I missing something?

**Comment by cajhin** [comment]
I can recreate the problem. Ick. Definitely a regression, somehow the line breaks cause a new problem.
Will fix that asap, this is a heavy bug.

Short term workaround, put all characters in one line like 
```
ALPHA_FROM   Q W E R T   Y U I O P  A S D F G   H J K L ;   Z X C V B   N M
ALPHA_TO     Q W F P G   J L U Y ;  A R S T D   H N E I O   Z X C V B   K M
ALPHA_END
```

**Comment by cajhin** [comment]
fixed
get v91 here: https://github.com/cajhin/capsicain/tree/master/x64/Release
Very minor change, but major embarrassment. 
Thanks for noticing.

**Comment by mittsquared** [comment]
Sorry for the delay; can confirm, everything works as intended for this use case. Thank you for the fast fix!

**Comment by ArijanJ** [comment]
Please update the official github release, I spent way too long trying to fix this until I looked at the closed issues.
