### ISSUE TITLE
Suggestion: take control of new images linked from wiki

### ISSUE THREAD

**Issue by bitoj** [cajhin/capsicain#40]
Wiki page [How to find the Key Labels](https://github.com/cajhin/capsicain/wiki/How-to-find-the-Key-Labels) now contains links to two images in a separate [gist](https://gist.github.com/bitoj/83c6749d4ef00a92094cbd08c96b816f). Consider copying the images or cloning the gist, so that all wiki content is under your control. (Assuming you approve of the change...)

Production details are in the gist.

**Comment by cajhin** [comment]
done. Thanks.
