### ISSUE TITLE
minimize to tray

### ISSUE THREAD

**Issue by yoloswaggerboy69** [cajhin/capsicain#41]
is there a quick way to minimize capsicain to try so that it doesn't occupy space in the taskbar ?

**Comment by cajhin** [comment]
ESC+T Toggles Traybar<>Taskbar

you can also put
GLOBAL StartInTraybar
onto your config

**Comment by yoloswaggerboy69** [comment]
YOU ABSOLUTE LEGEND!
 Thank you so much.
