### ISSUE TITLE
Altchars not sent with french layout

### ISSUE THREAD

**Issue by Yomgui33** [cajhin/capsicain#43]
I've been trying to send altchars to remap some accented characters using a french layout, and nothing happens. But once I switch to an english (US) layout, the character is properly sent.

I'm using this simple combo:

COMBO E [&... ....] > altChar(0233)

Did I miss something? Or is this a capsicain issue?

**Comment by cajhin** [comment]
Strange. I tried your combo, with French, German and US layout, and it worked in all three cases.
The only difference I see is that with German (and French?) Right Alt is "AltGR", which is slightly different from regular Alt in Euro languages, but the Windows Alt-Numpad combos work just the same.
