### ISSUE TITLE
Send key-press on config switch

### ISSUE THREAD

**Issue by MatejKafka** [cajhin/capsicain#45]
In my current AHK config, I have a small GUI indicator in the corner that changes color based on currently selected config, so I always know which config is active. I'd like to replicate this with Capsicain.

I understand that Capsicain cannot control GUI directly, so I want to use an AHK script that listens for a synthetic key-press from Capsicain (something like F13) and changes the GUI indicator accordingly. Therefore, I need to send a key-press on every config change.

I could define custom hotkeys for config switching and send the keystroke there, but if I then switched using the default Escape+<num> hotkeys, the GUI indicator would not be updated.

Is it possible to send the keystroke automatically, or is using custom hotkeys for switching the only option?

**Comment by cajhin** [comment]
Layer number is shown in the traybar
