### ISSUE TITLE
Document that key sequence delay defaults to 5 milliseconds

### ISSUE THREAD

**Issue by MatejKafka** [cajhin/capsicain#47]
UPDATE: oops, sorry, discovered the `OPTION DelayForKeySequenceMS` option. I think it should be documented that it defaults to 5 milliseconds, not zero, which came to me as a bit of a surprise. :)

---

First of all, sorry, this is my 4th opened issue today :) - I don't expect you to immediately go around fixing these, and so far, I'm quite happy with how Capsicain works right now, I'm just opening the issues as I'm encountering them when porting my oversized config from AHK. :)

---

With a hotkey like `COMBO f [^^^& .... ....] > moddedKey(0 + &)`, which maps `CapsLock-f` to `)`, the repeat rate is quite low compared to pressing Shift-0 directly, or using AHK, and the key repeats for some time after it is released on my machine.

Also, when using `altChar`, or entering a longer sequence of chars using `sequence`, the key-press latency is perceptibly higher then for shorter remaps - for `sequence`, the characters are appearing on-screen one by one.

Is this to be expected, or is it a bug / issue on my system?

**Comment by cajhin** [comment]
done
