### ISSUE TITLE
Rewire OnTap does not trigger combo

### ISSUE THREAD

**Issue by mrcruz** [cajhin/capsicain#55]
In my current config, I use `key(')`  as `MOD10` for navigation. But I'm also used to use it as a deadkey for latters like á and é. 

Consider the following config:

```  
REWIRE     '       MOD10       '
COMBO   '     [....] > deadkey(A)  
COMBO deadkey-A     A []  >  altChar(0225) 
```

I would expect that with a tap of `key(')`  I would get a deadkey(A) set. What happens instead is that it is never set and I just get a  `key(')`. 

Is this a bug or am I pushing the boundaries of the current syntax?

**Comment by cajhin** [comment]
please reopen if this is still an issue
