### ISSUE TITLE
How to remap media keys to open other app?

### ISSUE THREAD

**Issue by Shnxxx** [cajhin/capsicain#57]
I have this mechanical keyboard, which is unfortunately doesn't have its own software yet, and would like to remap my media keys to open other apps.

Is this possible to your software?

Thank you!

EDIT:
I tried looking here : [I cannot find the label for my special key](https://github.com/cajhin/capsicain/wiki/How-to-find-the-Key-Labels#i-cannot-find-the-label-for-my-special-key), but after pressing the special key, the debugger couldn't recognize it.

I have four special keys, Music, Email, Calculator, and File manager. Tried pressing them while the debugger is opened, all of the was not recognized.

Thank you again!

**Comment by cajhin** [comment]
If the keys don't show up in debug mode, it won't work. See https://github.com/cajhin/capsicain/wiki/X-doesn't-work

Try Autohotkey, maybe you're lucky
