### ISSUE TITLE
Modifier remapping is broken?

### ISSUE THREAD

**Issue by Telvran** [cajhin/capsicain#6]
If I load the example INI, these don't seem to be working?

MODIFIER    TAB    LCTRL   TAB
MODIFIER    CAPS   MOD9    NOP

TAB and CAPS still appear as [M:0] in debug. I can't get MODIFIER to do anything no matter what I try. Something like "COMBO A [...&] > key(B)" does work though.

Also, consider add some basic REWIRE stuff to the example INI. Many people, like myself, who stumble upon this software are looking to do basic key remaps when. Perhaps AHK is giving issues and we end up here. Having the most essential syntax tucked away in your master file instead of the tutorial will turn new users away.

**Comment by cajhin** [comment]
Oops that is a bit embarassing. Thanks for telling.
Keyword "MODIFIER" was renamed to "REWIRE" 2 years ago and I never updated all the examples.

On top of that, the config logic picks out all the known keywords, and just ignores the rest.
There should be a syntax check, for everyone who is not me...

Again, thanks a lot. This is a stupid simple mistake that probably everybody runs into immediately.

**Comment by Telvran** [comment]
Happy to help. This is a nice little program. I have a bunch of half-finished gaming projects that can really benefit from low-level remapping. Keep up the good work :)
