### ISSUE TITLE
Send media key

### ISSUE THREAD

**Issue by sleepntsheep** [cajhin/capsicain#62]
Hello, is it possible to send media key with capsicain? 
for example ALT+J for volume down
I am not sure if this has already been mentioned in the manual sorry.

**Comment by cajhin** [comment]
Yes, Windows defines some media keys that capsicain can send.
Check https://github.com/cajhin/capsicain/blob/master/capsicain/scancodes.cpp
Key labels would be VOLUMEDOWN, NEXTTRACK etc.

//ALT+J for volume down
COMBO J [&...] >key(VOLUMEDOWN)

**Comment by sleepntsheep** [comment]
Thanks!
