### ISSUE TITLE
Slow startup time?

### ISSUE THREAD

**Issue by jacksongoode** [cajhin/capsicain#63]
Not sure why but setting capsicain to start causes massive stuttering on boot. Is this expected?

**Comment by cajhin** [comment]
(very late reply)
This is unexpected, I have never observed this myself and there is no other report of this.

Anyone, please say so if you can see stuttering on boot that appears to be related to capsicain.
In theory, the client typically starts in under one second and shouldn't be able to cause extended stuttering.

**Comment by jacksongoode** [comment]
Hello, I'll see if I can take a log of this. If you have any suggestions for utilities it would be great to hear. But there appears to be a clear throttling of the UI while capsaicin starts.

**Comment by cajhin** [comment]
I'd take it out of auto-startup (try task manager > startup tab),
reboot and check that the PC boots without stuttering,
start capsicain manually (should be very quick, way under 1 second).

If all is well without capsicain, 
put it back into auto-startup,
reboot and check for stuttering.

IF the first reboot was fine and the second was stuttering... let me know, I'll need more info
