### ISSUE TITLE
Help with my custom configuration

### ISSUE THREAD

**Issue by andarms** [cajhin/capsicain#7]
Hello, I love what you  had done.  

I bougth a cheap 60% keyboard with awful  layout  for arrows keys and with caspicain i coluld made my  custom layout using SPACE as a modifier 

```
REWIRE	SPACE	MOD9	SPACE

COMBO   J  [...& .... ....] > key (LEFT)
COMBO   L  [...& .... ....] > key (RIGHT)  
COMBO   I  [...& .... ....] > key (UP)
COMBO   K  [...& .... ....] > key (DOWN)
COMBO   Y  [...& .... ....] > key (HOME)
COMBO   U  [...& .... ....] > key (END)
```

but I have a few questions:
- why [...& .... ....]  is MOD9?
- is posible to map LCTRL to D while holding down  MOD9 (SPACE)?
- how to map Ñ to ALT + N?
- how to map accented vowels (á, é, í, ó, ú) to ALT + VOWELS?
- is posible to add media controls like play/pause, prev track, next track?

**Comment by cajhin** [comment]
> Hello, I love what you had done.
Thanks for the feedback - there's not much of it so I just code what I need myself.

>I bougth a cheap 60% keyboard with awful layout for arrows keys and with caspicain i coluld made my custom layout using SPACE as a modifier
Try it out. I myself stepped away from the space bar; when typing I hit it very often and very fast, which tends to result in accidents when it is overloaded (Example, I type "on a jam", high chance that it results in "on a[LEFT]am" with your layout). But everybody types differently.
My "cursor control power key" is CapsLock, I've been happy with it for 15 years now.


>    why [...& .... ....] is MOD9?
it's position #9 (the mod symbols go from right to left, it is in essence a number). MOD1..8 are the standard modifiers (shift ctrl win alt)

>    is posible to map LCTRL to D while holding down MOD9 (SPACE)?
Like "LCtrl+Mod9 > key(D) ?
No. You can't map pure modifier combos to something. Again, error prone (e.g. I keep hitting shift+alt, which toggles the Windows language, argh). And I don't need it, there are so many possible combos available.

>    how to map Ñ to ALT + N?
I guess that's the [;] key on a Spanish keyboard?
; [....] > combo(ALT+N)
(off the top of my head, I didn't verify this is correct)

>    how to map accented vowels (á, é, í, ó, ú) to ALT + VOWELS?
You cannot map characters. You can only map KEYS. I don't know how you produce a "á" with your language setting.
Basically, look at the capsicain console, press [ESC]+D for debug output, then press the key you want to do something.
That's the key (scancode label) you want.
Maybe I didn't understand the question.

>    is posible to add media controls like play/pause, prev track, next track?
You mean make the physical [play] button do something? Depends.
Again, open the debug console, press the key, and see if something happens.
Some keys send out a proper keyboard scan code, but some special keys send a USB signal that is not "keyboard". Like your mouse buttons, they come over USB, but they are not processed by the keyboard stack. If capsicain doesn't see it, you cannot remap it.

If you want to SEND media keys, look at this file:
https://github.com/cajhin/capsicain/blob/master/capsicain/scancodes.cpp
The codes on the right, like "PLAYPAUSE", are the scancode labels that you can put in your capsicain.ini
Like "P [&.&.] > key(PLAYPAUSE)     #LCTRL+LALT+P sends play/pause

**Comment by DGCupit** [comment]
Any thoughts of making an AHK script to Capsicain converter?

Also, is there a list of Keys, like on the AHK site? Or are all the keynamings the same?

I'm not trying to do anything fancy at all - I just want to remap common WASD FPS shooter key layout to a right-side keyboard layout. I normally use AHK for this, but it seems that some games just completely ignore AHK - Like the new Cyberpunk 2077. AHK does nothing in this game.

Here's my AHK script. It's really, really simple - ScrollLock is my toggle to activate / deactivate mappings:

ScrollLock::Suspend
Up::w
Down::s
Left::a
Right::d
Enter::r
Home::i
End::e
\::LShift
RShift::c
RCtrl::Space
PgUp::TAB
PgDn::t
Ins::f
Del::LAlt
BackSpace::Esc
Numpad0::v
Numpad1::q
Numpad3::b
Numpad4::LCtrl
Numpad5::m
Numpad7::g
Numpad8::x
Numpad9::z
NumpadDot::j
NumpadEnter::Enter
w::Up
s::Down
a::Left
d::Right
