### ISSUE TITLE
ERROR: Received unexpected SC_NOP Key Stroke code 0. Ignoring this:

### ISSUE THREAD

**Issue by Deaquay** [cajhin/capsicain#72]
When i start capsicain with a simple code like:
```
[CONFIG_1]
REWIRE A Z
```
or even with an empty .ini, it just spams this in the main window
```
ERROR: Received unexpected SC_NOP Key Stroke code 0. Ignoring this:

new keyboard: IBM keyboard
```
over and over again. So fast you cant even read what the message says if you dont stop the window from scrolling.
Any fixes?

**Comment by cajhin** [comment]
What kind of keyboard is this, and which Windows version?
The error results from an explicit check that the input is not byte 0 (my understanding is that no keyboard should send 0).

**Comment by Deaquay** [comment]
This is with a Steelseries Apex Pro, running on:
Windows 10 Pro
Version 21H2
OS build 19044.1586

**Comment by cajhin** [comment]
Do you have any other keyboard you could test it with, to determine if the Apex Pro is "weird", or if the problem is something other than the keyboard?

**Comment by Deaquay** [comment]
I'll go through my storage and grab a ps2 keyboard and try. That keyboard should be as vanilla as it gets.

**Comment by Deaquay** [comment]
Sorry for the really late reply. My PS2 Keyboard was in storage so couldn't get to it. But now I've tried with only PS2 Keyboard, and i still get the same error. https://imgur.com/giujuFu
Could it be any other peripherals disturbing? I don't have much though, and they aren't anything special, just xbox controller and usb dongle for steelseries arctis 9.
I didn't have the apex pro connected while retrying btw, even restarted pc after changing keyboards to be safe.

It would be awesome if this issue could be resolved. I'm after such a simple thing and I can't seem to find a solution not involving autohotkey. I just want to rebind ctrl+esc to just send esc command since I somehow always unintentionally press ctrl when pressing escape which messes me up in some games, and is generally just really anoying.

Having the option to change actuation point on the apex pro helps to some degree, but if I set actuation point so low that I dont press ctrl when pressing escape, then I instead miss clicking ctrl due to not pressing it far enough down.

**Comment by Deaquay** [comment]
Got any solution or alternative for the ctrl+esc binding?
Cheers

**Comment by cajhin** [comment]
So if I understand you correctly, then something on your PC sends the scancode "0" all the time.
The specification says "00 is normally an error code"
0 is undefined and not a valid scancode. I wouldn't know what to do with it, so I keep ignoring it.
I wouldn't recommend capsicain in that case, I don't understand what is happening. 
Something like COMBO ESC [..&.] > moddedKey(ESC + ....)  might work on a normal PC, but I didn't test it.
