### ISSUE TITLE
`startMinimized` not work in Windows 11 22H2

### ISSUE THREAD

**Issue by u-Sir** [cajhin/capsicain#77]
config in `capsicain.ini`:
```
GLOBAL StartMinimized
                #start capsicain minimized in the taskbar
GLOBAL StartInTraybar
                #start capsicain with a traybar icon instead. Toggle traybar<>taskbar with ESC+T

[CONFIG_1]
#OPTION debug
OPTION configName QwertzJ-KingCon
REWIRE CAPS LWIN
COMBO LWIN [...& ....] > key(CAPS)  #[RSHIFT] + [LWIN] = CapsLock.
```
windows terminal always shows up on startup, if close the window, capsicain exited too.
![图片](https://user-images.githubusercontent.com/93647031/203949479-c71b898a-9a96-4616-8d52-b23811d8517d.png)

**Comment by u-Sir** [comment]
finally, i figured it out. Just `run as administrator`

**Comment by cajhin** [comment]
Run as admin should not be necessary. I run it on the same Win10 version without admin, on startup the Window pops up, capsicain initializes, then the Window minimizes.

I notice you're running in the 'special' shell from github. I have that installed, too, but it's not used by default when capsicain starts. I only start it manually. I guess that might be the reason why it won't minimize.

**Comment by cajhin** [comment]
update: don't run as admin, see this instead
https://github.com/cajhin/capsicain/wiki/Installation#windows-11-version-22h2-cannot-minimize-to-tray

**Comment by u-Sir** [comment]
> update: don't run as admin, see this instead https://github.com/cajhin/capsicain/wiki/Installation#windows-11-version-22h2-cannot-minimize-to-tray

thx👍
