### ISSUE TITLE
Cannot hide console on Windows 11

### ISSUE THREAD

**Issue by Lingxi-Li** [cajhin/capsicain#80]
No issue on Windows 10, but on Windows 11 (Version 22H2, to be specific), there seems to be no way to hide the console. Despite the global options

~~~
GLOBAL StartInTraybar
GLOBAL StartMinimized
~~~

capsicain still starts with console in my face. When started, [ESC] + [T] is able to minimize the console, but the icon still remains on task bar, which is quite annoying.

**Comment by Lingxi-Li** [comment]
OK, I seem to have located the root cause. Windows 11 comes with the following console setting.

![image](https://user-images.githubusercontent.com/11997203/206620118-f8735530-4c87-4488-bde8-ec61594db782.png)

The issue is with "Windows Terminal" which is default for me.

**Comment by cajhin** [comment]
Thank you, that was *very* helpful.

(hours later, I managed to restore my Win11 VM and upgrade to 22H2, where the Terminal is indeed now the default)

I'll put a notice on the front page. The short version is:
make a shortcut, and explicitly start capsicain in the console host
Target: 
  conhost.exe c:\your\path\capsicain exe
Start in:
  c:\your\path\
