### ISSUE TITLE
Feature request: config for specific keyboard

### ISSUE THREAD

**Issue by u-Sir** [cajhin/capsicain#82]
as a laptop user, I hope to set different config for each keyboard when external keyboard plugged in.

**Comment by cajhin** [comment]
You can restrict capsicain to one keyboard, and leave other keyboards standard.
OPTION processOnlyFirstKeyboard
https://github.com/cajhin/capsicain/wiki/Keyword%3A-OPTION

You cannot automatically switch between configurations when you switch keyboards.

**Comment by cajhin** [comment]
You now can have specific configs for each keyboard, see wiki
OPTION IncludeDeviceID {searchString}
