### ISSUE TITLE
ERROR: Received unexpected SC_NOP Key Stroke code 0

### ISSUE THREAD

**Issue by drivermix** [cajhin/capsicain#84]
Hello,

First off, this is an awesome project you've got going here!

While I haven't had any issues with it on my old Asus laptop, I just got myself a new notebook (Samsung Galaxy Book S), and capsicain simply refuses to... I don't know, "interface with it"... It's a nothing special notebook with an out-of-the-box Win 10 factory installation on it. No special keyb related programs, no tweaks, nothing out of the ordinary. But as I attempt to launch capsicain, it spits out the  following over and over until I close the command prompt:

ERROR: Received unexpected SC_NOP Key Stroke code 0. Ignoring this.

new keyboard: IBM keyboard

---------------
I have no reason to believe that the laptop's keyboard is faulty, as it seems to work fine for all intents and purposes. Besides, this is happening even when I connect an external keyboard (a simple Dell unit). In fact, this is the setup I have on my old laptop; I used an external keyb almost exclusively, and capsicain works fine and out of the box (no errors of any kind).

When attempting to get some kind of response from capsicain as it's just outputting the above error message continuously, nothing short of closing the command prompt entirely helps to stop the error being output. Tried Ctrl-C and all the capsicain's Esc+ shortcuts, all to no avail. FYI, I'm using the latest (v93) version. Even tried to start it with completely empty .ini file. The problem persists. I doubt it's capsicain's fault per se; it's likely to do with the way these thin notebooks are pre-configured somehow. You know, you can't open them up or upgrade them, and this one doesn't even support reinstalling the OS from a flash stick. Otherwise, it's a perfectly usable notebook.

Anyway, any advice would be appreciated. Thanks in advance.

**Comment by cajhin** [comment]
Hi, I would double check that you have installed the Interception driver correctly, from an admin console, and rebooted since then.

**Comment by kelsoz** [comment]
I have the same erro~~
but I don't know how to fix it.


ERROR: Received unexpected SC_NOP Key Stroke code 0. Ignoring this.
new keyboard: IBM keyboard

**Comment by cajhin** [comment]
did you do these steps, especially 4-7 ?
https://github.com/cajhin/capsicain/wiki/Installation
