### ISSUE TITLE
REWIRE works great, but COMBO doesn't seem to do anything

### ISSUE THREAD

**Issue by bamwu** [cajhin/capsicain#88]
```
GLOBAL IniVersion WIN2MAC

GLOBAL ActiveConfigOnStartup 1

[CONFIG_1]

REWIRE LCTRL NOP
REWIRE LWIN LCTRL

REWIRE RCTRL NOP
REWIRE RWIN RCTRL

COMBO 3 [&&] > moddedKey(PRINT + .... .... &...)

```

Trying to get a mac-style screenshot happening on the combo line.

I've tried [&^&] as well.

Any ideas?

On a Mac, it's SHIFT + COMMAND + 3

**Comment by cajhin** [comment]
Sorry, no idea. I tried your combo out, and Shift+Control+3 sends Alt+Print ("copy active window").
Did you try out with a simpler combo, like  COMBO 3 [] > moddedKey( A + &) 
( [3] sends Shift A )
