### ISSUE TITLE
Can you hide the program to the system tray?

### ISSUE THREAD

**Issue by Possibly-Insane** [cajhin/capsicain#9]
Thanks for making this, as AHK doesn't work in too many programs.

Is it possible to make capsicain not show up in my taskbar, instead have it be in the system tray like AHK? I've tried to achieve this with trayit but that requires you to move it there yourself, was wondering if it could be done automatically.

Something I had in my AHK script was capslock as backspace, haven't been able to replicate this here so I achieved it through a AHK script launched by capsicain. Is there a way for to do this without involving AHK?

**Comment by cajhin** [comment]
Hi

it's only possible with code changes (and it is a very unpleasant Windows GUI coding task).
I don't want to use it myself, but you're not the first to ask and I see why you'd want it.
Maybe one day...

Try
REWIRE CAPS  BSP
in your .ini
This should do what you want (I didn't try it out, let me know if it doesn't work)

**Comment by Possibly-Insane** [comment]
Ah that's a shame that there isn't an easy way to do it.

Yep that worked, I was typing BACKSPACE instead of BSP haha.

**Comment by cajhin** [comment]
TODO: tray icon (started looking into it, garkhx that's some ugly code)

**Comment by cajhin** [comment]
You can now use a (very basic) traybar icon.
Ini setting GLOBAL StartInTraybar
Toggle with ESC+T

Would be nice if the icon showed the current layer, maybe some day...

(clicking on the traybar icon does not do anything. Console apps are not aware of any Windows events)
