### ISSUE TITLE
Vim leader key mapping

### ISSUE THREAD

**Issue by pl643** [cajhin/capsicain#90]
Is it possible to use capsicain to do the below mapping?

# Leader Key Keyboard - inspired from the vi editor's mapleader feature
 - promote tapping/demote chording
 - designate a key as the "Leader" key
   - a good leader key is one that is not used frequently and easy to access:
      -  ; and , are good candidates
   - tapping the leader key 2 times will produce the actual key

# Mappings
 - tapping the \<leader> and the below key will change the state for the next key pressed:
   - f - ctrl
   - d - shift
   - s - alt
   - a - Winkey

   - e - sends <ESC> key
   - r - return/enter
   - m - executes macro/combo - a way to send keys sequence or combo
   - v - vim layer navigation

# Example key sequences
 - \<leader>\<leader>  -> \<leader>
 - \<leader>fa        -> ctrl-a
 - \<leader>da        -> A
 - \<leader>sa        -> alt-a
 - \<leader>aa        -> win-a
 - \<leader>mp        -> sends "MySecretPassword\<Enter>"
 - \<leader>m1        -> sends "Ctrl-Alt-F1"
 - \<leader>v         -> enters vim navition layer
                        - hjkl - left,down,up,right
			- e/d  - home/end
			- space - page down
			- b - page up
			- 1-9 - ctrl 1-9 for chrome tabs
			- x - exits vim layer

**Comment by cajhin** [comment]
Most of it should be possible, not very elegant but doable with deadkeys
See https://github.com/cajhin/capsicain/wiki/Function%3A-deadkey%28%29

What won't work is the generic modifier combos ("leader key, F" -> Ctrl is applied to the next key). You'd have to create a rule for every specific Ctrl+key combo (like: leader Key, F, S -> ctrl+S

Comment here if you have questions.
