### ISSUE TITLE
ZBoard Merc Remapping WEBHOME, etc

### ISSUE THREAD

**Issue by johndavis23** [cajhin/capsicain#92]
I'm running a ZBoard Merc on Windows 11 with what I assume is the default HID keyboard driver. When using javascript or another tool to identify my keystrokes on the wads game pad it identifies them as WEBHOME, WEBSEARCH, etc.  When using debug mode, they don't seem to come up in the console. Is it possible to remap these? I attempted as follows to no avail:

```
#         Key           To Key     (IfTapped) (IfTap+Hold)
REWIRE    WEBHOME       W      
REWIRE    WEBBACK       A
REWIRE    WEBSTOP       S
REWIRE    WEBFORWARD    D
REWIRE    WEBSEARCH     E
REWIRE    WEBREFRESH    Q
```

PowerToys Keyboard Manager is able to remap these, but it fails when you try to hold two of them down at once.

**Comment by cajhin** [comment]
If it doesn't show up in debug mode, then you cannot deal with it in capsicain.
Your game pad buttons are probably mapped to virtual keys, at a later stage, that capsicain does not interact with.

I happily used Autohotkey to map my old xbox controller buttons to keys; this no longer work right with the new xbox controller.
