### ISSUE TITLE
Rewiring to shifts doesn't work

### ISSUE THREAD

**Issue by sandoru** [cajhin/capsicain#95]
It seems that rewiring any keys to SHIFT keys like

REWIRE  LALT LSHIFT
REWIRE  KANA RSHIFT

don't work. 
(Applications keep reacting to the rewired LALT as to LALT.)
Rewiring LALT and KANA to other keys including modifiers (LWIN, LCTRL, etc.) works properly.

**Comment by cajhin** [comment]
When you start or switch to your layer, you should see the message
"ERROR: Bad rewire / key mapping: lalt lshift"

"lshift" is not a known key label. Press left shift in debug mode (ESC+D) to see the label for that key (it's LSHF, not very intuitive, but I was trying to keep the labels short)

**Comment by sandoru** [comment]
Thanks, LSHF is working!
(It seems that "bad rewire" message didn't appear though.)
